import jsPDF from 'jspdf';
import QRCode from 'qrcode';
import { EmailRequest } from '../types';
import { format } from 'date-fns';

export const generateRequestPDF = async (request: EmailRequest): Promise<Blob> => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  
  // Add ONGC header
  pdf.setFontSize(20);
  pdf.setTextColor(30, 58, 138); // ONGC blue
  pdf.text('ONGC Email Automation Portal', pageWidth / 2, 20, { align: 'center' });
  
  pdf.setFontSize(16);
  pdf.setTextColor(0, 0, 0);
  pdf.text('Email Request Form', pageWidth / 2, 35, { align: 'center' });
  
  // Add horizontal line
  pdf.setLineWidth(0.5);
  pdf.line(20, 40, pageWidth - 20, 40);
  
  let yPosition = 55;
  
  // Request details
  pdf.setFontSize(12);
  pdf.setFont(undefined, 'bold');
  pdf.text('Request ID:', 20, yPosition);
  pdf.setFont(undefined, 'normal');
  pdf.text(request.id, 60, yPosition);
  
  yPosition += 10;
  pdf.setFont(undefined, 'bold');
  pdf.text('Type:', 20, yPosition);
  pdf.setFont(undefined, 'normal');
  pdf.text(request.type.replace(/_/g, ' ').toUpperCase(), 60, yPosition);
  
  yPosition += 10;
  pdf.setFont(undefined, 'bold');
  pdf.text('Status:', 20, yPosition);
  pdf.setFont(undefined, 'normal');
  pdf.text(request.status.toUpperCase(), 60, yPosition);
  
  yPosition += 10;
  pdf.setFont(undefined, 'bold');
  pdf.text('Submitted by:', 20, yPosition);
  pdf.setFont(undefined, 'normal');
  pdf.text(request.userName, 60, yPosition);
  
  yPosition += 10;
  pdf.setFont(undefined, 'bold');
  pdf.text('Date:', 20, yPosition);
  pdf.setFont(undefined, 'normal');
  pdf.text(format(request.createdAt, 'dd/MM/yyyy HH:mm'), 60, yPosition);
  
  yPosition += 20;
  
  // Form data section
  pdf.setFont(undefined, 'bold');
  pdf.text('Form Details:', 20, yPosition);
  yPosition += 15;
  
  pdf.setFont(undefined, 'normal');
  Object.entries(request.formData).forEach(([key, value]) => {
    pdf.setFont(undefined, 'bold');
    pdf.text(`${key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())}:`, 25, yPosition);
    pdf.setFont(undefined, 'normal');
    
    const textLines = pdf.splitTextToSize(String(value), pageWidth - 100);
    pdf.text(textLines, 100, yPosition);
    yPosition += textLines.length * 5 + 5;
  });
  
  // Add QR code
  try {
    const qrCodeData = await QRCode.toDataURL(`ONGC-REQ-${request.id}`);
    pdf.addImage(qrCodeData, 'PNG', pageWidth - 50, 50, 30, 30);
  } catch (error) {
    console.error('Failed to generate QR code:', error);
  }
  
  // Footer
  yPosition = pdf.internal.pageSize.getHeight() - 30;
  pdf.setFontSize(10);
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by ONGC Email Automation Portal', pageWidth / 2, yPosition, { align: 'center' });
  pdf.text(`Generated on: ${format(new Date(), 'dd/MM/yyyy HH:mm')}`, pageWidth / 2, yPosition + 10, { align: 'center' });
  
  return pdf.output('blob');
};

export const downloadPDF = async (request: EmailRequest) => {
  const pdfBlob = await generateRequestPDF(request);
  const url = URL.createObjectURL(pdfBlob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `ONGC-Email-Request-${request.id}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};